apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-builder
  namespace: argocd
  labels:
    cluster: minikube
    app: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/charts
    targetRevision: main
    path: charts/gitops-builder
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true 
